name: CI-CD-EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ“¥ Descargar cÃ³digo del repositorio
        uses: actions/checkout@v4

      - name: ğŸ” Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: ğŸ› ï¸ Crear repositorio ECR si no existe
        run: |
          aws ecr describe-repositories --repository-names flask-app --region us-east-1 || aws ecr create-repository --repository-name flask-app --region us-east-1

      - name:  Autenticarse en Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: ğŸ—ï¸ Construir imagen Docker
        run: |
          docker build -t flask-app ./app

      - name: ğŸ“¦ Etiquetar imagen para ECR
        run: |
          docker tag flask-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - name: ğŸš€ Subir imagen a Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - name: ğŸ”„ Actualizar kubeconfig para conectarse a EKS
        run: aws eks update-kubeconfig --name project03-eks

      - name: ğŸš¢ Desplegar aplicaciÃ³n en EKS
        run: kubectl apply -f k8s/
